# -*- coding: utf-8 -*-
TAG_42_IIN                          = "\x42"      # Issuer Identification Number (IIN)
TAG_4F_AID                          = "\x4F"      # Application Identifier(AID)
TAG_50_AppLabel                     = "\x50"      # Application label
TAG_57_Track2EquData                = "\x57"      # Track 2 Equivalent Data
TAG_5A_PAN                          = "\x5A"      # Application Primary Account Number(PAN)
TAG_5F20_HolderName                 = "\x5F\x20"  # Cardholder Name
TAG_5F24_AppExpDate                 = "\x5F\x24"  # Application Expiration Date
TAG_5F25_AppEffectiveDate           = "\x5F\x25"  # Application Effective Date
TAG_5F28_IssuerCountryCode          = "\x5F\x28"  # Issuer Country Code
TAG_5F2A_TransCurrencyCode          = "\x5F\x2A"  # Transaction Currency Code
TAG_5F2D_LanguagePrefer             = "\x5F\x2D"  # Language Preference
TAG_5F30_ServiceCode                = "\x5F\x30"  # Service Code
TAG_5F34_PANSeqNo                   = "\x5F\x34"  # Application Primary Account Number Sequence Number
TAG_5F36_TransCurrencyExp           = "\x5F\x36"  # Transaction Currency Exponent
TAG_5F50_IssuerURL                  = "\x5F\x50"  # Issuer URL
TAG_5F53_IBAN                       = "\x5F\x53"  # International Bank Account Number (IBAN)
TAG_5F54_BIC                        = "\x5F\x54"  # Bank Identifier Code (BIC)
TAG_5F55_IssuerCountryCodeA2        = "\x5F\x55"  # Issuer Country Code (alpha2 format)
TAG_5F56_IssuerCountryCodeA3        = "\x5F\x56"  # Issuer Country Code (alpha3 format)
TAG_5F57_AccountType                = "\x5F\x57"  # Account Type
TAG_61_AppTemplate                  = "\x61"      # Application Template
TAG_6F_FCITemplate                  = "\x6F"      # File Control Infomation Template
TAG_70_AEFDataTemplate              = "\x70"      # Application Elementary File Data Template
TAG_71_ScriptTemplate1              = "\x71"      # Issuer Script Template 1
TAG_72_ScriptTemplate2              = "\x72"      # Issuer Script Template 2
TAG_73_DirDiscTemplate              = "\x73"      # Directory Discretionary Template
TAG_77_RspMsgTemplateFmt2           = "\x77"      # Response Message Template Format 2
TAG_80_RspMsgTemplateFmt1           = "\x80"      # Response Message Template Format 1
TAG_81_AmountB                      = "\x81"      # Amount, Authorised(Binary)
TAG_82_AIP                          = "\x82"      # Application Interchange Profile
TAG_83_CmdTemplate                  = "\x83"      # Command Template
TAG_84_DFName                       = "\x84"      # Dedicated File(DF) Name
TAG_86_IssuerScriptCmd              = "\x86"      # Issuer Script command 文档规定最大261
TAG_87_AppPriorIndicator            = "\x87"      # Application Priority Indicator
TAG_88_SFI                          = "\x88"      # Short File Identifier
TAG_89_AuthCode                     = "\x89"      # Authorisation Code
TAG_8A_AuthRspCode                  = "\x8A"      # Authorisation Response Code
TAG_8C_CDOL1                        = "\x8C"      # Card Risk Management Data Object List 1(CDOL1)
TAG_8D_CDOL2                        = "\x8D"      # Card Risk Management Data Object List 2(CDOL2)
TAG_8E_CVMList                      = "\x8E"      # Cardholder Verification Method(CVM) List
TAG_8F_CAPubKeyIndex                = "\x8F"      # Certification Authority Public Key Index
TAG_90_IssuerPubKeyCert             = "\x90"      # Issuer Public Key Certificate
TAG_91_IssuerAuthData               = "\x91"      # Issuer Authentication Data
TAG_92_IssuerPubKeyRem              = "\x92"      # Issuer Public Key Remainder
TAG_93_SSAD                         = "\x93"      # Signed Static Application Data
TAG_94_AFL                          = "\x94"      # Application File Locator(AFL)
TAG_95_TVR                          = "\x95"      # Terminal Verification Results
TAG_97_TDOL                         = "\x97"      # Transaction Certificate Data Object List(TDOL)
TAG_98_TCHashValue                  = "\x98"      # Transaction Certificate(TC) Hash Value
TAG_99_TransPINData                 = "\x99"      # Transaction Personal Identification Number(PIN) Data
TAG_9A_TransDate                    = "\x9A"      # Transaction Date
TAG_9B_TSI                          = "\x9B"      # Transaction Status Information
TAG_9C_TransType                    = "\x9C"      # Transaction Type
TAG_9D_DDFName                      = "\x9D"      # Directory Definition File(DDF) Name
TAG_9F01_AcquirerId                 = "\x9F\x01"  # Acquirer Identifier
TAG_9F02_AmountN                    = "\x9F\x02"  # Amount, Authorised(Numeric)
TAG_9F03_AmountOtherN               = "\x9F\x03"  # Amount, Other(Numeric)
TAG_9F04_AmountOtherB               = "\x9F\x04"  # Amount, Other(Binary)
TAG_9F05_AppDiscData                = "\x9F\x05"  # Application Discretionary Data
TAG_9F06_AID                        = "\x9F\x06"  # Application Identifier(AID)
TAG_9F07_AUC                        = "\x9F\x07"  # Application Usage Control
TAG_9F08_AppVerCard                 = "\x9F\x08"  # Application Version Number, Card
TAG_9F09_AppVerTerm                 = "\x9F\x09"  # Application Version Number, Terminal
TAG_9F0B_HolderNameExt              = "\x9F\x0B"  # Cardholder Name Extended
TAG_9F0D_IACDefault                 = "\x9F\x0D"  # Issuer Action Code - Default
TAG_9F0E_IACDenial                  = "\x9F\x0E"  # Issuer Action Code - Denial
TAG_9F0F_IACOnline                  = "\x9F\x0F"  # Issuer Action Code - online
TAG_9F10_IssuerAppData              = "\x9F\x10"  # Issuer Application Data
TAG_9F11_IssuerCodeTableIndex       = "\x9F\x11"  # Issuer Code Table Index
TAG_9F12_AppPrefName                = "\x9F\x12"  # Application Preferred Name
TAG_9F13_LastOnlineATC              = "\x9F\x13"  # Last Online Application Transaction Counter(ATC) Register
TAG_9F14_LCOL                       = "\x9F\x14"  # Lower Consecutive Offline Limit
TAG_9F15_MerchantCategoryCode       = "\x9F\x15"  # Merchant Category Code
TAG_9F16_MerchantId                 = "\x9F\x16"  # Merchant Identifier
TAG_9F17_PINTryCounter              = "\x9F\x17"  # Personal Identification Number(PIN) Try Counter
TAG_9F18_ScriptId                   = "\x9F\x18"  # Issuer Script Identifier
TAG_9F1A_TermCountryCode            = "\x9F\x1A"  # Terminal Country Code
TAG_9F1B_TermFloorLimit             = "\x9F\x1B"  # Terminal Floor Limit
TAG_9F1C_TermId                     = "\x9F\x1C"  # Terminal Identification
TAG_9F1D_TermRistManaData           = "\x9F\x1D"  # Terminal Risk Management Data
TAG_9F1E_IFDSerNo                   = "\x9F\x1E"  # Interface Device(IFD) Serial Number
TAG_9F1F_Track1DiscData             = "\x9F\x1F"  # Track 1 Discretionary Data
TAG_9F20_Track2DiscData             = "\x9F\x20"  # Track 2 Discretionary Data
TAG_9F21_TransTime                  = "\x9F\x21"  # Transaction Time
TAG_9F22_CAPubKeyIndex              = "\x9F\x22"  # Certification Authority Public Key Index
TAG_9F23_UCOL                       = "\x9F\x23"  # Upper Consecutive Offline Limit
TAG_9F26_AC                         = "\x9F\x26"  # Application Cryptogram
TAG_9F27_CID                        = "\x9F\x27"  # Cryptogram information Data
TAG_9F2D_ICCPinEncPubKeyCert        = "\x9F\x2D"  # ICC PIN Encipherment Public Key Certificate
TAG_9F2E_ICCPinEncPubKeyExp         = "\x9F\x2E"  # ICC PIN Encipherment Public Key Exponent
TAG_9F2F_ICCPinEncPubKeyRem         = "\x9F\x2F"  # ICC PIN Encipherment Public Key Remainder
TAG_9F32_IssuerPubKeyExp            = "\x9F\x32"  # Issuer Public Key Exponent
TAG_9F33_TermCapability             = "\x9F\x33"  # Terminal Capabilities
TAG_9F34_CVMResult                  = "\x9F\x34"  # Cardholder Verification Method(CVM) Results
TAG_9F35_TermType                   = "\x9F\x35"  # Terminal Type
TAG_9F36_ATC                        = "\x9F\x36"  # Application Transaction Counter(ATC)
TAG_9F37_TermRand                   = "\x9F\x37"  # Unpredictable Number
TAG_9F38_PDOL                       = "\x9F\x38"  # Processing Options Data Object List(PDOL)
TAG_9F39_POSEntryMode               = "\x9F\x39"  # Point-of-Service(POS) Entry Mode
TAG_9F3A_AmountRefCurrency          = "\x9F\x3A"  # Amount, Reference Currency
TAG_9F3B_AppRefCurrency             = "\x9F\x3B"  # Appilcation Reference Currency
TAG_9F3C_TransRefCurrency           = "\x9F\x3C"  # Transaction Reference Currency
TAG_9F3D_TransRefCurrencyExp        = "\x9F\x3D"  # Transaction Reference Currency Exponent
TAG_9F40_TermCapabilityExt          = "\x9F\x40"  # Additional Terminal Capabilities
TAG_9F41_TransSeqCounter            = "\x9F\x41"  # Transaction Sequence Counter
TAG_9F42_AppCurrencyCode            = "\x9F\x42"  # Application Currency Code
TAG_9F43_AppRefCurrencyExp          = "\x9F\x43"  # Application Reference Currency Exponent
TAG_9F44_AppCurrencyExp             = "\x9F\x44"  # Application Curerncy Exponent
TAG_9F45_DAC                        = "\x9F\x45"  # Data Authentication Code
TAG_9F46_ICCPubKeyCert              = "\x9F\x46"  # ICC Public Key Certificate
TAG_9F47_ICCPubKeyExp               = "\x9F\x47"  # ICC Public Key Exponent
TAG_9F48_ICCPubKeyRem               = "\x9F\x48"  # ICC Public Key Remainder
TAG_9F49_DDOL                       = "\x9F\x49"  # Dynamic Data Object List(DDOL)
TAG_9F4A_SDATagList                 = "\x9F\x4A"  # Static Data Authentication Tag List
TAG_9F4B_SDAData                    = "\x9F\x4B"  # Signed Dynamic Application Data
TAG_9F4C_ICCDynNumber               = "\x9F\x4C"  # ICC Dynamic Number
TAG_9F4D_LogEntry                   = "\x9F\x4D"  # Log Entry
TAG_9F4E_MerchantName               = "\x9F\x4E"  # Merchant Name and Location
TAG_9F4F_LogFmt_I                   = "\x9F\x4F"  # Log Format
TAG_9F51_AppCurrencyCode_I          = "\x9F\x51"  # Application Currency Code(Pboc2.0 卡内部数据)
TAG_9F5A_IssuerURL2                 = "\x9F\x5A"  # Issuer URL2
TAG_9F5D_OfflineAmount              = "\x9F\x5D"  # qPBOC: Available Offline spending Amount
TAG_9F61_HolderId                   = "\x9F\x61"  # pboc2.0 Holder Id
TAG_9F62_HolderIdType               = "\x9F\x62"  # pboc2.0 Holder Id Type
TAG_9F63_CardProducId               = "\x9F\x63"  # pboc2.0 卡产品标识信息
TAG_9F66_ContactlessSupport         = "\x9F\x66"  # pboc2.0 contactless support flag
TAG_9F69_CardAuthRelatedData        = "\x9F\x69"  # Card Authentication Related Data
TAG_9F6C_CardTransQualifiers        = "\x9F\x6C"  # Card Transaction Qualifiers
TAG_9F6D_ECResetThreshold_I         = "\x9F\x6D"  # EC Reset Threshold
TAG_9F74_ECIssuerAuthCode           = "\x9F\x74"  # EC Issuer Authorization Code
TAG_9F77_ECBalanceLimit_I           = "\x9F\x77"  # EC Balance Limit
TAG_9F78_ECSingleTransLimit_I       = "\x9F\x78"  # EC Single Transaction Limit
TAG_9F79_ECBalance_I                = "\x9F\x79"  # EC Balance
TAG_9F7A_ECTermSupportIndicator     = "\x9F\x7A"  # EC Terminal Support Indicator
TAG_9F7B_ECTermTransLimit           = "\x9F\x7B"  # EC Terminal Transaction Limit
TAG_A5_FCIProprietaryTemplate       = "\xA5"      # File Control Information(FCI) Proprietary Template
TAG_BF0C_FCIIssuerDiscData          = "\xBF\x0C"  # File Control Information(FCI) Issuer Discretionary Data
TAG_DF31_ScriptResult               = "\xDF\x31"  # Script result 广发后台设定脚本执行结果Tag为DF31
TAG_DF4D_LoadLogEntry               = "\xDF\x4D"  # Load Log Entry(圈存日志入口)
TAG_DF4F_LoadLogFmt_I               = "\xDF\x4F"  # Load Log Format(圈存日志格式)
TAG_DF71_AppCurrencyCode2_I         = "\xDF\x71"  # Application Second Currency Code(Pboc3.0 双币电子现金卡内部数据)
TAG_DF79_ECBalance2_I               = "\xDF\x79"  # EC Balance(第二货币)
# boc2.0或Emv冲突, 自定义Tag使用两字节Tag, 且第二字= 节的最高位设为1, 此约定限Tag长度不能超过2字节
TAG_DFXX_DefaultDDOL                = "\xDF\x81"  # default ddol
TAG_DFXX_DefaultTDOL                = "\xDF\x82"  # default tdol
TAG_DFXX_EncOnlinePIN               = "\xDF\x83"  # enciphered online pin
TAG_DFXX_OnlinePINSupport           = "\xDF\x84"  # online pin support, 1:支持 0:不支持
TAG_DFXX_MaxTargetPercentage        = "\xDF\x87"  # Maximum Target Percentage to be used for Biased Random Selection
TAG_DFXX_RandomSelThreshold         = "\xDF\x88"  # Threshold Value for Biased Random Selection
TAG_DFXX_TargetPercentage           = "\xDF\x8A"  # Target Percentage to be Used for Random
TAG_DFXX_TACDefault                 = "\xDF\x8C"  # TAC-default
TAG_DFXX_TACDenial                  = "\xDF\x8D"  # TAC-denial
TAG_DFXX_TACOnline                  = "\xDF\x8E"  # TAC-online
TAG_DFXX_LocalLanguage              = "\xDF\x90"  # 本地语言(操作员), ISO-639-1
TAG_DFXX_ReaderCapability           = "\xDF\x91"  # 读卡器能力 1:只支持磁卡 2:只支持IC卡 3:支持组合式Mag/IC读卡器 4:支持分离式Mag/IC读卡器
TAG_DFXX_VoiceReferralSupport       = "\xDF\x92"  # Voice referral支持 1:支持 2:不支持,缺省approve 3:不支持,缺省decline
TAG_DFXX_ForceOnlineSupport         = "\xDF\x93"  # 强制联机支持 1:支持 0:不支持
TAG_DFXX_ForceAcceptSupport         = "\xDF\x94"  # 强制接受支持 1:支持 0:不支持
TAG_DFXX_TransLogSupport            = "\xDF\x95"  # 1:终端支持交易流水记录 0:不支持
TAG_DFXX_BlacklistSupport           = "\xDF\x96"  # 1:终端支持黑名单检查 0:不支持
TAG_DFXX_SeparateSaleSupport        = "\xDF\x97"  # 1:支持分开消费检查 0:不支持
TAG_DFXX_AppConfirmSupport          = "\xDF\x98"  # 1:支持应用确认 0:不支持应用确认
TAG_DFXX_PinpadLanguage             = "\xDF\x99"  # ISO-639-1, Pinpad支持的语言或可以支持持卡人的语言
TAG_DFXX_LanguageUsed               = "\xDF\x9A"  # 最终使用的语言(持卡人)，iso-639-1
TAG_DFXX_ECTermSupportIndicator     = "\xDF\x9B"  # EC Terminal Support Indicator
TAG_DFXX_PdolDataBlock              = "\xDF\x9C"  # PDOL数据块, CDA使用
TAG_DFXX_Cdol1DataBlock             = "\xDF\x9D"  # CDOL1数据块, CDA使用
TAG_DFXX_Cdol2DataBlock             = "\xDF\x9E"  # CDOL2数据块, CDA使用
TAG_DFXX_ASI                        = "\xDF\x9F"  # 应用选择指示
TAG_DFXX_KeyModulus                 = "\xDF\xA0"  # CA公钥模数
TAG_DFXX_KeyExp                     = "\xDF\xA1"  # CA公钥指数
TAG_DFXX_KeyRid                     = "\xDF\xA2"  # CA公钥所属RID
TAG_DFXX_KeyHashAlgo                = "\xDF\xA3"  # CA公钥Hash算法
TAG_DFXX_KeyAlgo                    = "\xDF\xA4"  # CA公钥算法
TAG_DFXX_KeyExpireDate              = "\xDF\xA5"  # CA公钥有效期
TAG_DFXX_KeyHashValue               = "\xDF\xA6"  # CA公钥Hash值
TAG_DFXX_RandForSelect              = "\xDF\xA7"  # 随机选择处理中终端生成的随机数
TAG_DFXX_PinBypassBehavior          = "\xDF\xA8"  # PIN bypass特性 0:每次bypass只表示该次bypass 1:一次bypass,后续都认为bypass
TAG_DFXX_ECTransFlag                = "\xDF\xAA"  # EC交易标志 0:非EC交易 1:EC交易 2:GPO卡片返回EC授权码,但未走EC通道
TAG_DFXX_TransType                  = "\xDF\xAB"  # 交易类型, 低位等于T9C值, 高位用于区分商品/服务 IC/Mag
TAG_DFXX_ECBalanceOriginal          = "\xDF\xAC"  # 交易前EC余额
TAG_DFXX_TermCtlsCapMask            = "\xDF\xE6"  # 终端非接能力屏蔽位, 9F66映像, 表示终端有其中相应位表示的能力
TAG_DFXX_TermCtlsAmountLimit        = "\xDF\xE7"  # 终端非接交易限额
TAG_DFXX_TermCtlsOfflineAmountLimit = "\xDF\xE8"  # 终端非接脱机交易限额
TAG_DFXX_TermCtlsCvmLimit           = "\xDF\xE9"  # 终端非接CVM限额
TAG_DFXX_TransRoute                 = "\xDF\xEA"  # 交易走的路径, 0:接触Pboc(标准DC或EC) 1:非接触Pboc(标准DC或EC) 2:qPboc联机 3:qPboc脱机 4:qPboc拒绝
TAG_DFXX_ScriptPackage71            = "\xDF\xF1"  # 71脚本包, 内存若干71脚本, 注意,不要修改Tag值, 必须为DFF1
TAG_DFXX_ScriptPackage72            = "\xDF\xF2"  # 72脚本包, 内存若干72脚本, 注意,不要修改Tag值, 必须为DFF2
